//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Input_Materails
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<decimal> Total_Price { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public Nullable<int> IdMaterials { get; set; }
    
        public virtual Raw_Materials Raw_Materials { get; set; }
        public virtual Raw_Materials Raw_Materials1 { get; set; }
        public virtual Raw_Materials Raw_Materials2 { get; set; }
    }
}
