//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutPutOfProduct
    {
        public int Id { get; set; }
        public string Name_Product { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<decimal> Total_Salary { get; set; }
        public Nullable<System.DateTime> Isert_date { get; set; }
        public Nullable<int> Id_Product { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Product Product1 { get; set; }
        public virtual Product Product2 { get; set; }
    }
}
