//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raw_Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Raw_Materials()
        {
            this.Input_Materails = new HashSet<Input_Materails>();
            this.Input_Materails1 = new HashSet<Input_Materails>();
            this.Input_Materails2 = new HashSet<Input_Materails>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> Sup_Id { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<System.DateTime> DateIsertion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Input_Materails> Input_Materails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Input_Materails> Input_Materails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Input_Materails> Input_Materails2 { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Supplier Supplier1 { get; set; }
        public virtual Supplier Supplier2 { get; set; }
    }
}
